// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy86A1gDwNSfevWtJvmuUSpK7Osje5RLY',
    appId: '1:212534578385:web:4e9cb25b630ddf5127c9f0',
    messagingSenderId: '212534578385',
    projectId: 'flutter-firebase-course-a425e',
    authDomain: 'flutter-firebase-course-a425e.firebaseapp.com',
    storageBucket: 'flutter-firebase-course-a425e.firebasestorage.app',
    measurementId: 'G-Z9KPFXVWXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4oXHQ-t5-ZdhWvdazkcyI1PPsKYcsHKY',
    appId: '1:212534578385:android:2889b81a833b99c627c9f0',
    messagingSenderId: '212534578385',
    projectId: 'flutter-firebase-course-a425e',
    storageBucket: 'flutter-firebase-course-a425e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPVvs4M3uSXy322uI-Y1Do3K__Fw5mv2E',
    appId: '1:212534578385:ios:e4ea05131534889527c9f0',
    messagingSenderId: '212534578385',
    projectId: 'flutter-firebase-course-a425e',
    storageBucket: 'flutter-firebase-course-a425e.firebasestorage.app',
    iosBundleId: 'com.flutter.course.flutterFirebaseCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPVvs4M3uSXy322uI-Y1Do3K__Fw5mv2E',
    appId: '1:212534578385:ios:e4ea05131534889527c9f0',
    messagingSenderId: '212534578385',
    projectId: 'flutter-firebase-course-a425e',
    storageBucket: 'flutter-firebase-course-a425e.firebasestorage.app',
    iosBundleId: 'com.flutter.course.flutterFirebaseCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy86A1gDwNSfevWtJvmuUSpK7Osje5RLY',
    appId: '1:212534578385:web:0de02bd2e33cc08c27c9f0',
    messagingSenderId: '212534578385',
    projectId: 'flutter-firebase-course-a425e',
    authDomain: 'flutter-firebase-course-a425e.firebaseapp.com',
    storageBucket: 'flutter-firebase-course-a425e.firebasestorage.app',
    measurementId: 'G-8NV5X6N7QY',
  );
}
