// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7vFX91K-NBXFgbDy_03kw5qsHGHD2oyw',
    appId: '1:476147597784:web:a5b5271ccc272cbea4b2ad',
    messagingSenderId: '476147597784',
    projectId: 'flutter-playground-fireb-11278',
    authDomain: 'flutter-playground-fireb-11278.firebaseapp.com',
    storageBucket: 'flutter-playground-fireb-11278.firebasestorage.app',
    measurementId: 'G-P6BWYVNK8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzgVk2o8gGOVHybdCwvKTNmG4rU3bV26Y',
    appId: '1:476147597784:android:31892321f98e52b1a4b2ad',
    messagingSenderId: '476147597784',
    projectId: 'flutter-playground-fireb-11278',
    storageBucket: 'flutter-playground-fireb-11278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKZ5ktqIZ9oS6mjNwQvrc0XszEq4-Fh7g',
    appId: '1:476147597784:ios:22880d2ae75713e3a4b2ad',
    messagingSenderId: '476147597784',
    projectId: 'flutter-playground-fireb-11278',
    storageBucket: 'flutter-playground-fireb-11278.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKZ5ktqIZ9oS6mjNwQvrc0XszEq4-Fh7g',
    appId: '1:476147597784:ios:22880d2ae75713e3a4b2ad',
    messagingSenderId: '476147597784',
    projectId: 'flutter-playground-fireb-11278',
    storageBucket: 'flutter-playground-fireb-11278.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7vFX91K-NBXFgbDy_03kw5qsHGHD2oyw',
    appId: '1:476147597784:web:3cff913506054b70a4b2ad',
    messagingSenderId: '476147597784',
    projectId: 'flutter-playground-fireb-11278',
    authDomain: 'flutter-playground-fireb-11278.firebaseapp.com',
    storageBucket: 'flutter-playground-fireb-11278.firebasestorage.app',
    measurementId: 'G-2T6YVZEBC6',
  );

}