// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr6I1AUDiJK1J8-sPdS5PHOWGI_MFcg8Q',
    appId: '1:224665283154:web:ffaa2c558e199ab9434d8b',
    messagingSenderId: '224665283154',
    projectId: 'fir-playground-fd073',
    authDomain: 'fir-playground-fd073.firebaseapp.com',
    storageBucket: 'fir-playground-fd073.firebasestorage.app',
    measurementId: 'G-2PM4KQRQ1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn9qs_piMVJ737oE06YVrJon8G6tbXDXc',
    appId: '1:224665283154:android:8c3e65c03557994c434d8b',
    messagingSenderId: '224665283154',
    projectId: 'fir-playground-fd073',
    storageBucket: 'fir-playground-fd073.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPWY9eq-A6iEwyaQ5RVPLJ-qfm53_6GkM',
    appId: '1:224665283154:ios:80ffb6b696eab810434d8b',
    messagingSenderId: '224665283154',
    projectId: 'fir-playground-fd073',
    storageBucket: 'fir-playground-fd073.firebasestorage.app',
    iosBundleId: 'com.example.firebasePlayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPWY9eq-A6iEwyaQ5RVPLJ-qfm53_6GkM',
    appId: '1:224665283154:ios:80ffb6b696eab810434d8b',
    messagingSenderId: '224665283154',
    projectId: 'fir-playground-fd073',
    storageBucket: 'fir-playground-fd073.firebasestorage.app',
    iosBundleId: 'com.example.firebasePlayground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr6I1AUDiJK1J8-sPdS5PHOWGI_MFcg8Q',
    appId: '1:224665283154:web:4bf1a83230f64c99434d8b',
    messagingSenderId: '224665283154',
    projectId: 'fir-playground-fd073',
    authDomain: 'fir-playground-fd073.firebaseapp.com',
    storageBucket: 'fir-playground-fd073.firebasestorage.app',
    measurementId: 'G-F3L0R1Q38N',
  );
}
